env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
  - plugin:vue/base
  - plugin:vuetify/base
ignorePatterns:
  - node_modules/
  - dist/
  - public/
  - src/client/components/models/bnf/worker/**/*.js
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
}
