export const grammarTypeItems = [
    {
        name: "No grammar validator",
        code: "no-grammar-validator",
    },
    // {
    //     name: "BNF",
    //     code: "bnf",
    // },
    {
        name: "Langium",
        code: "langium",
    }
];

export const hyperParameterPresets = {
    "gpt-4o": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "gpt-4o-2024-11-20": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "gpt-4o-2024-08-06": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "gpt-4o-2024-05-13": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "chatgpt-4o-latest": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "gpt-4o-mini": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "gpt-4o-mini-2024-07-18": {
        temperature: 0.1,
        maximumLength: 4095,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "bigcode/starcoder2-7b": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "bigcode/starcoder2-15b": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "bigcode/starcoder2-3b": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "bigcode/starcoder2-15b-instruct-v0.1": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "Qwen/QwQ-32B-Preview": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "Qwen/Qwen2.5-32B-Instruct": {
        temperature: 0.5,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "Qwen/Qwen2.5-72B-Instruct": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "Qwen/Qwen2.5-Coder-32B-Instruct": {
        temperature: 0.5,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "Qwen/Qwen2.5-Coder-7B-Instruct": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/Llama-3.1-70B-Instruct": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/Llama-3.1-8B-Instruct": {
        temperature: 0.5,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/Llama-3.3-70B-Instruct": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/CodeLlama-13b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "codellama/CodeLlama-13b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/CodeLlama-7b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "codellama/CodeLlama-7b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/CodeLlama-34b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "codellama/CodeLlama-34b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "meta-llama/CodeLlama-70b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "codellama/CodeLlama-70b-Instruct-hf": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "mistralai/Mistral-7B-Instruct-v0.1": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "mistralai/Mistral-7B-Instruct-v0.2": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "mistralai/Mistral-7B-Instruct-v0.3": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "mistralai/Mistral-Nemo-Instruct-2407": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "mistralai/Mistral-Large-Instruct-2411": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.8,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
    "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF": {
        temperature: 0.1,
        maximumLength: 4095,
        topK: 50,
        topP: 0.9,
        repetitionPenalty: 0,
        seed: 7,
        stopSequences: [";", "###"],
    },
};

